import type React from 'react';
import type { Metadata } from 'next';
import NavBar from './components/NavBar';
import './globals.css';

export const metadata: Metadata = {
	title: 'Pennies',
	description: 'An Experiment Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" data-theme="pastel">
			<body className="prose !max-w-none">
				<NavBar />
				<main className="container mx-auto pt-4">{children}</main>
			</body>
		</html>
	);
}
